version: '3.8'

services:
  web:
 deploy:
 resources:
 limits:
 memory: 512m
 cpus: '0.5'
 deploy:
 resources:
 limits:
 memory: 512m
 cpus: '0.5'
 deploy:
 resources:
 limits:
 memory: 512m
 cpus: '0.5'
 deploy:
 resources:
 limits:
 memory: 512m
 cpus: '0.5'
    build: .
    ports:
      - "127.0.0.1:15000:5000"
    environment:
      - FLASK_ENV=development
    volumes:
      - .:/app
    command: python app.py

